
services:
  webapi:
    image: gamestore:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql
    environment:
      ConnectionStrings__DefaultConnection: "Server=localhost,1433;Database=GameStoreDatabase2;User Id=sa;Password=P@ssw0rd;TrustServerCertificate=True;"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:

