name: Publish Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
      - 'Dockerfile'
      - '.dockerignore'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Build Docker image
      run: |
        docker build -t gamestore:latest .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag gamestore:latest ${{ secrets.DOCKER_HUB_USERNAME }}/gamestore:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gamestore:latest
